version: "3.9"

services:
  app:
    build: .
    container_name: vainobus-api
    hostname: vainobus-api
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8095:80"
    volumes:
      - .:/var/www/html 